module.exports = {
    transferenciaPessoa: [
        "JEFFERSON", "CAVALCA", "CAVALCANT", "MARLLON", "MAIA", "ANDRE", "MACHADO", "SILVA", 
        "CAMILA", "ALMEIDA", "SANTOS", "LUCAS", "FERREIRA", "PEREIRA", "MARTINS", "RODRIGUES", 
        "FREITAS", "PINHEIRO", "COSTA", "GOMES", "SOUZA", "MENEZES", "LOPES", "RIBEIRO", "OLIVEIRA", 
        "GONÇALVES", "MARTINS", "SILVEIRA", "VIEIRA", "BARBOSA", "GARCIA", "ALVES", "CARVALHO", 
        "PEREIRA", "DOMINGOS", "COSTA", "FERREIRA", "CAMPOS", "SANTOS", "RAMOS", "TEIXEIRA", "LIMA", 
        "CORREIA", "GOMES", "MACEDO", "BRITO", "LOPES", "ROCHA", "MOURA", "FERNANDES", "SIMÕES", 
        "JUNIOR", "ANDRADE", "CARDOSO", "NASCIMENTO"
    ],
    uber: [
        "UBER", "99 POP", "CABIFY", "LIFT", "TAXI", "TAKI", "MOBI", "TAXI RÁPIDO", "SPLIT", 
        "FARE", "RAPPI", "SPLIT", "JOKER", "BOLT", "DIDI", "GOLFE", "CARREFOUR", "STREET CABS", 
        "ZUMO", "VIAJEM", "MUV", "SCOOTER", "VAN", "MOTOBOY", "URBANO", "FASTTAXI", "CARSHARE", 
        "YELLOW", "CARGO", "SPLITPAY", "BICICLETAS", "FRETE", "SKIP", "TROCO", "TAXI FÁCIL", 
        "TRANSPORTA", "ANIMAL", "LOJA", "FRETAMENTO", "AUTO VÁLIDO", "SIMPLES TAXI", "MOTOTÁXI", 
        "MOTO FRETE", "TRANSPORTE", "TRANSPORTES", "REDE TAXI", "TRANSPORTE VÁLIDO", "MOTO FÁCIL", 
        "DROPSHIPPING", "VAN TÁXI"
    ],
    alimentacao: [
        "REFEIÇÕES", "LANCHONETE", "ALIMENTAÇÃO", "MERCADO", "SUPERMERCADO", "COMIDA", "RESTAURANTE", 
        "FAST FOOD", "SANDUICHE", "PIZZA", "LIVRARIA", "CAFÉ", "CAFETERIA", "COMPRAS", "ANGELONI", 
        "COOPER", "CASA DE SUCOS", "LIVRARIA", "SUSHI", "JAPONES", "CAFÉ DA MANHÃ", "ALMOÇO", "JANTAR", 
        "HAMBÚRGUER", "FRANGO", "SALADA", "SOPA", "DOCE", "DOCERIA", "BISCOITO", "GELATINA", "TORTA", 
        "PÃO", "QUEIJO", "CERVEJA", "VINHO", "LIMONADA", "COCA COLA", "PEPSI", "SUCO", "XIS", 
        "ESFIHA", "MILHO", "CAFÉ EXPRESSO", "PÃO DE QUEIJO", "PASTEL", "SANDUÍCHE", "LANCHE", "SUCO NATURAL", 
        "FRUTA", "TACOS", "BURGUER", "SNACK", "LANCHES RÁPIDOS", "TREMOR", "BAR LOUNGE", "KIBBE"
    ],
    apostas: [
        "APOSTAS", "TIGGER", "BET", "CASINO", "ROULETTE", "JOGO", "BINGO", "CARTA", "ROULETTE", 
        "BET365", "BETFAIR", "VIRTUAL", "LOTERIA", "SORTEIO", "ROULETTE ONLINE", "ROULETTE VIRTUAL", 
        "ROULETTE REAL", "CASINO ONLINE", "POKER", "BLACKJACK", "TEXAS HOLD'EM", "ROULETTE RUSSIA", 
        "POKERSTARS", "BOOKMAKER", "SPORTS BETTING", "JOQUEI", "PUNTER", "SLOTS", "JACKPOT", "BOLÃO", 
        "PINBALL", "APOSTA EM ESCOLHA", "CASINO LIVE", "SLOT MACHINE", "EXPOBET", "BOLÃO ONLINE", 
        "VIRTUAL BET", "CASINO NOITE", "BET ONLINE", "APOSTA ESPORTIVA", "CASINO VEGAS", "BETTING", 
        "JOGO DE DADOS", "BLACKJACK REAL", "BINGO ONLINE", "JOGO DAS CARTAS", "GANHAR NO APOSTO", "CLUBE DE APOSTAS", 
        "MEXER NO JOGO", "FLUXO ONLINE", "BOLETIM"
    ],
    aluguel: [
        "ACRC", "IMOBILIÁRIA", "ALUGUEL", "ALUGA", "ALUGUEL RESIDENCIAL", "ALUGUEL COMERCIAL", "ALUGA-SE", 
        "ALUGUEL APARTAMENTO", "ALUGUEL CASA", "CONDOMÍNIO", "ALUGUEL LOJA", "ALUGUEL MÓVEL", "ALUGUEL COMERCIAL", 
        "ALUGUEL TRILHA", "ALUGUEL APTO", "ALUGUEL RESIDENCIAL CASA", "ALUGUEL FEVEREIRO", "ALUGUEL PRÉDIO", 
        "ALUGUEL ESTÁGIO", "ALUGUEL PRÉDIO COMERCIAL", "ALUGUEL NOVO", "ALUGUEL DE ESCRITÓRIO", "ALUGUEL QUARTO", 
        "ALUGUEL PRÉDIO LOJA", "PAGAMENTO ALUGUEL", "ALUGUEL FINAL", "RENT", "RENTA", "ALUGUEL DE APARTAMENTO", 
        "CASA PARA ALUGAR", "ALUGUEL IMÓVEL", "ALUGUEL REFORMA", "ALUGUEL QUADRA", "ALUGUEL LOCAL", 
        "ALUGUEL SINGULAR", "FATURA ALUGUEL", "RENTA IMÓVEL", "ALUGUEL ESCRITÓRIO", "PROPRIETÁRIO ALUGUEL", 
        "ALUGUEL DO APARTAMENTO", "ALUGUEL PRAZO", "ALUGUEL ESCOLA", "ALUGUEL RESIDENCIAL LOJA", 
        "RENTAL", "TAXA ALUGUEL", "ALUGUEL ALUGA", "ALUGUEL PARCELADO", "ALUGUEL A PRAZO", "PAGAMENTO IMÓVEL"
    ],
    agua: [
        "SAMAe", "ÁGUA", "ÁGUA E SANEAMENTO", "BOLETO ÁGUA", "FATURA ÁGUA", "CONTA ÁGUA", "ÁGUA SEMED", 
        "ÁGUA E SANEAMENTO", "ÁGUA E ENERGIA", "FATURA ÁGUA", "ÁGUA COMPANHIA", "ÁGUA SEM FIOS", 
        "PREÇO ÁGUA", "AGUAS DA CIDADE", "ÁGUA SANITÁRIA", "CONSULTA ÁGUA", "BOLETO AGUA", "ÁGUA ATUAL", 
        "SAMAEMAX", "ÁGUA TEMA", "ÁGUA DE CONTA", "CONTROLE ÁGUA", "DEBITO ÁGUA", "SANEAMENTO", "ÁGUA E CANAL", 
        "CONSUMO ÁGUA", "VIAÇÃO ÁGUA", "ÁGUA MÍNIMA", "FATURA COMPANHIA", "PREÇO DE ÁGUA", "CONTA DE ÁGUA", 
        "LEITURA ÁGUA", "SANEAMENTO DE ÁGUA"
    ]
}
