module.exports = {
  uber: [
    /UBER/i, /99 POP/i, /CABIFY/i, /LIFT/i, /TAXI/i, /TAKI/i, /MOBI/i, 
    /TAXI RÁPIDO/i, /SPLIT/i, /FARE/i, /RAPPI/i, /JOKER/i, /BOLT/i, 
    /DIDI/i, /TRIP/i, /UBER \*TRIP/i, /AUTO POSTO/i
  ],
  alimentacao: [
    /Refeicoes/i,/Rex Pad&conf /i,/Angeloni/i,/Casa Do Pao Lanchonete/i,/Pizzaria /i,/Ifood/i,/Atacadao/i,/REFEIÇÕES/i, /LANCHONETE/i, /ALIMENTAÇÃO/i, /MERCADO/i, /SUPERMERCADO/i, 
    /COMIDA/i, /RESTAURANTE/i, /FAST FOOD/i, /SANDUICHE/i, /PIZZA/i, 
    /LIVRARIA/i, /CAFÉ/i, /CAFETERIA/i, /COMPRAS/i, /ANGELONI/i, /COOPER/i, 
    /CASA DE SUCOS/i, /SUSHI/i, /JAPONES/i, /CAFÉ DA MANHÃ/i, /ALMOÇO/i, 
    /JANTAR/i, /HAMBÚRGUER/i, /FRANGO/i, /SALADA/i, /SOPA/i, /DOCE/i, 
    /DOCERIA/i, /BISCOITO/i, /GELATINA/i, /TORTA/i, /PÃO/i, /QUEIJO/i, 
    /CERVEJA/i, /VINHO/i, /LIMONADA/i, /COCA COLA/i, /PEPSI/i, /SUCO/i, 
    /XIS/i, /ESFIHA/i, /MILHO/i, /CAFÉ EXPRESSO/i, /PÃO DE QUEIJO/i, 
    /PASTEL/i, /SANDUÍCHE/i, /LANCHE/i, /SUCO NATURAL/i, /FRUTA/i, /TACOS/i, 
    /BURGUER/i, /SNACK/i, /LANCHES RÁPIDOS/i, /TREMOR/i, /BAR LOUNGE/i, 
    /KIBBE/i, /AQUA MAGIC/i, /PIZZARIA/i, /IFOOD/i, /ATACADAO/i, /TONHO GAS/i
  ],
  apostas: [
    /Apostaraiz/i,/Conection Pay/i,/Gd  Money/i,/Df Participacoes/i,/Lisboapay/i,/M C R T3 Investimentos/i,/All Bets/i,/Instantpay Ltda/i,/APOSTAS/i, /TIGGER/i, /BET/i, /CASINO/i, /ROULETTE/i, /JOGO/i, /BINGO/i, 
    /CARTA/i, /BET365/i, /BETFAIR/i, /VIRTUAL/i, /LOTERIA/i, /SORTEIO/i, 
    /ROULETTE ONLINE/i, /ROULETTE VIRTUAL/i, /ROULETTE REAL/i, /CASINO ONLINE/i, 
    /POKER/i, /BLACKJACK/i, /TEXAS HOLD'EM/i, /ROULETTE RUSSIA/i, /POKERSTARS/i, 
    /BOOKMAKER/i, /SPORTS BETTING/i, /JOQUEI/i, /PUNTER/i, /SLOTS/i, /JACKPOT/i, 
    /BOLÃO/i, /PINBALL/i, /APOSTA EM ESCOLHA/i, /CASINO LIVE/i, /SLOT MACHINE/i, 
    /EXPOBET/i, /BOLÃO ONLINE/i, /VIRTUAL BET/i, /CASINO NOITE/i, /BET ONLINE/i, 
    /APOSTA ESPORTIVA/i, /CASINO VEGAS/i, /BETTING/i, /JOGO DE DADOS/i, 
    /BLACKJACK REAL/i, /BINGO ONLINE/i, /JOGO DAS CARTAS/i, /GANHAR NO APOSTO/i, 
    /CLUBE DE APOSTAS/i, /MEXER NO JOGO/i, /FLUXO ONLINE/i, /BOLETIM/i,
    /INSTANTPAY/i, /MANEYMASTER/i, /PAGALEVE/i, /MULTI CONECTIONS PAYMENTS/i,
    /ALL BETS/i, /DEMERGE/i, /M C R T3 INVESTIMENTO/i, /BET365/i,/DEMERGE/i
  ],
  aluguel: [
    /IMOVEIS BLUMENAU LTDA/i,/ACRC/i, /IMOBILIÁRIA/i, /ALUGUEL/i, /ALUGA/i, /ALUGUEL RESIDENCIAL/i, 
    /ALUGUEL COMERCIAL/i, /ALUGA-SE/i, /ALUGUEL APARTAMENTO/i, /ALUGUEL CASA/i, 
    /CONDOMÍNIO/i, /ALUGUEL LOJA/i, /ALUGUEL MÓVEL/i, /ALUGUEL COMERCIAL/i, 
    /ALUGUEL TRILHA/i, /ALUGUEL APTO/i, /ALUGUEL RESIDENCIAL CASA/i, 
    /ALUGUEL FEVEREIRO/i, /ALUGUEL PRÉDIO/i, /ALUGUEL ESTÁGIO/i, 
    /ALUGUEL PRÉDIO COMERCIAL/i, /ALUGUEL NOVO/i, /ALUGUEL DE ESCRITÓRIO/i, 
    /ALUGUEL QUARTO/i, /ALUGUEL PRÉDIO LOJA/i, /PAGAMENTO ALUGUEL/i, 
    /ALUGUEL FINAL/i, /RENT/i, /RENTA/i, /ALUGUEL DE APARTAMENTO/i, 
    /CASA PARA ALUGAR/i, /ALUGUEL IMÓVEL/i, /ALUGUEL REFORMA/i, /ALUGUEL QUADRA/i, 
    /ALUGUEL LOCAL/i, /ALUGUEL SINGULAR/i, /FATURA ALUGUEL/i, /RENTA IMÓVEL/i, 
    /ALUGUEL ESCRITÓRIO/i, /PROPRIETÁRIO ALUGUEL/i, /ALUGUEL DO APARTAMENTO/i, 
    /ALUGUEL PRAZO/i, /ALUGUEL ESCOLA/i, /ALUGUEL RESIDENCIAL LOJA/i, /RENTAL/i, 
    /TAXA ALUGUEL/i, /ALUGUEL ALUGA/i, /ALUGUEL PARCELADO/i, /ALUGUEL A PRAZO/i, 
    /PAGAMENTO IMÓVEL/i, /IMOVEIS BLUMENAU/i
  ],
  energia: [
    /SAMAE/i, /ÁGUA/i, /ÁGUA E SANEAMENTO/i, /BOLETO ÁGUA/i, /FATURA ÁGUA/i, 
    /CONTA ÁGUA/i, /ÁGUA SEMED/i, /ÁGUA E ENERGIA/i, /ÁGUA COMPANHIA/i, 
    /ÁGUA SEM FIOS/i, /PREÇO ÁGUA/i, /AGUAS DA CIDADE/i, /ÁGUA SANITÁRIA/i, 
    /CONSULTA ÁGUA/i, /BOLETO AGUA/i, /ÁGUA ATUAL/i, /SAMAEMAX/i, /ÁGUA TEMA/i, 
    /ÁGUA DE CONTA/i, /CONTROLE ÁGUA/i, /DEBITO ÁGUA/i, /SANEAMENTO/i, 
    /ÁGUA E CANAL/i, /CONSUMO ÁGUA/i, /VIAÇÃO ÁGUA/i, /ÁGUA MÍNIMA/i, 
    /FATURA COMPANHIA/i, /PREÇO DE ÁGUA/i, /CONTA DE ÁGUA/i, /LEITURA ÁGUA/i, 
    /SANEAMENTO DE ÁGUA/i, /LUZ/i, /ENERGIA/i, /CELESC/i, /COPEL/i, /CEMIG/i, 
    /ELETROPAULO/i, /LIGHT/i, /ENEL/i, /CPFL/i, /ENERGISA/i, /ELETROBRAS/i,
    /UNIFIQUE/i
  ],
  dogs: [
    /DOG/i, /CACHORRO/i, /CANIL/i, /PET/i, /VETERINÁRIO/i, /VETERINARIA/i, 
    /PETSHOP/i, /RAÇÃO/i, /ANIMAL/i, /BANHO E TOSA/i, /TOSA/i, /VACINA/i, 
    /CONSULTA VET/i, /REMÉDIO PET/i, /BRINQUEDO PET/i, /ACESSÓRIO PET/i
  ],
  gas: [
    /Tonho Gas /i,/GÁS/i, /BOTIJÃO/i, /GLP/i, /ULTRAGAZ/i, /LIQUIGÁS/i, /NACIONAL GÁS/i, 
    /SUPERGASBRAS/i, /FOGÃO/i, /COZINHA/i, /BOTIJÃO DE GÁS/i, /RECARGA GÁS/i,
    /TONHO GAS/i
  ],
  transferencias: [
    /PIX ENVIADO;58469458 JEFFERSON DA SILVA CAVALCANTE/i
  ],
  pix: [
    /PIX/i, /TRANSFERÊNCIA/i, /TED/i, /DOC/i, /ENVIO/i, /RECEBIDO/i
  ],
  investimentos: [
    /Criptomoedas/i,/INVEST/i, /AÇÃO/i, /AÇÕES/i, /BOLSA/i, /TESOURO/i, /FUNDO/i, /CDB/i, 
    /LCI/i, /LCA/i, /DEBÊNTURE/i, /RENDA FIXA/i, /RENDA VARIÁVEL/i, /FII/i, 
    /ETF/i, /PREVIDÊNCIA/i, /APLICAÇÃO/i, /RESGATE/i, /DIVIDENDO/i, /JUROS/i, 
    /CORRETORA/i, /BROKER/i, /TRADE/i, /TRADING/i, /STOCK/i, /BOND/i, 
    /TÍTULO/i, /TÍTULO PÚBLICO/i, /SELIC/i, /IPCA/i, /PREFIXADO/i, /PÓS-FIXADO/i
  ],
  saude: [
    /PANVEL/i, /FARMACIA/i, /DOCTOTECH/i, /CLINICA/i, /HOSPITAL/i, /MEDICO/i,
    /CONSULTA/i, /EXAME/i, /LABORATORIO/i, /MEDICAMENTO/i, /REMEDIO/i
  ],
  servicos: [
    /Unifique Telecomunicacoes/i,/Ebn         *spotify/i,/Auto Posto Blu Limitad Blumenau/i,/CONVENIO/i, /SPOTIFY/i, /RECARGA/i, /MILIUM/i, /Aqua Magic Blumenau/i, /Cg Lavanderia/i  
  ]
};